server:
  port: 8080

spring:
  sleuth:
    baggage:
      correlation-fields: Correlation-Id, Span-Id
      remote-fields: Correlation-Id, X-Forwarded-For

payment:
  service:
    url: http://localhost:8082/payments

logging:
  pattern:
    console: "%d | %-5level | %X{Correlation-Id:-},%X{spanId:-} | %X{X-Forwarded-For} | %msg%n"